# this is a comment
[first_table]
string = "some string"
number = 123
float = 123.456
boolean = true

# this is another comment
[second_table]
string = "another string"
number = 456
float = 456.789
boolean = false
